create database product;
use product;

create table SOFTWARE(
	SOFTWAREID INT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    VERSION VARCHAR(50),
    PUBLISHER VARCHAR(100),
    RELEASEDATE DATE,
    LICENSETYPE VARCHAR(50),
    PLATFORM VARCHAR(50),
    PRICE DECIMAL(10,2),
    DESCRIPTION TEXT
);

INSERT INTO SOFTWARE VALUES
(1,'MYSQL','8.3V','ORACLE','2023-11-16','COMMUNITY','SOFTWARE', 0,'MYSQL IS OPEN SOURCE SOFTWARE'),
(2,'WINDOWS','4.3V','MICROSOFT','2011-01-16','COMMUNITY','SOFTWARE', 987.38,'HELLO MICROSOFT'),
(3,'PYTHON','7.3V','AKHILESH','2016-08-01','COMMERCIAL','SOFTWARE', 98.98,'HERE PYTHON IS NOT A SNAKE '),
(4,'JAVA','10.3V','RAVI','2023-11-16','COMMERCIAL','HARDWARE', 9876543.93,'JAVA IS COFFEE SYMBOL')
;


SELECT * FROM SOFTWARE ;
SELECT * FROM SOFTWARE WHERE PRICE = 0 ; 
SELECT * FROM SOFTWARE WHERE PRICE > 1000 ;
SELECT * FROM SOFTWARE WHERE PRICE <= 1000;
SELECT * FROM SOFTWARE WHERE PRICE != 98.98;
SELECT * FROM SOFTWARE WHERE PLATFORM='SOFTWARE' AND PRICE=0;
SELECT * FROM SOFTWARE WHERE PLATFORM='SOFTWARE' OR PRICE=0;
SELECT * FROM SOFTWARE WHERE NOT NAME = 'MYSQL';

SELECT * FROM SOFTWARE WHERE DESCRIPTION LIKE 'h%';
SELECT * FROM SOFTWARE WHERE DESCRIPTION NOT LIKE 'h%';
SELECT * FROM SOFTWARE WHERE NAME LIKE '_Y%';
SELECT * FROM SOFTWARE WHERE PUBLISHER LIKE '%O%';

SELECT * FROM SOFTWARE WHERE PRICE BETWEEN 500 AND 1000;
DELETE FROM SOFTWARE WHERE SOFTWAREID=1 ;

COMMIT;

INSERT INTO SOFTWARE VALUES
(1,'MYSQL','8.3V','ORACLE','2023-11-16','COMMUNITY','SOFTWARE', 0,'MYSQL IS OPEN SOURCE SOFTWARE');
ROLLBACK;

CREATE INDEX PRODUCT_LIST ON SOFTWARE(NAME);
SELECT NAME,SUM(PRICE) FROM SOFTWARE WHERE PRICE>100 ORDER BY NAME DESC;

